### ISSUE TITLE
Error while importing: format not recognized

### ISSUE THREAD

**Issue by carlif** [ciscocms/cms-postman-collection#1]
When I try to import the collection, Postman gives me this error 

> Error while importing: format not recognized

Can the format be corrected? I am using the latest Postman version:
Postman for Windows
Version 7.22.1

**Comment by ryanquinlan** [comment]
@carlif How are you importing? Downloading the file, or having postman import the collection from a link?

I tested with Postman 7.22.1 for OS X and Windows using the import from link option and both were successful.

**Comment by carlif** [comment]
I apologize, I got it to work. I'm not sure what I was doing incorrectly before.
