### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Izya12** [ciscocms/cms-postman-collection#2]
Hello.
Will the collection of queries be updated?
At the moment, the collection is relevant for version **2.5** but for **2.9** it does not fit, some of the requests are missing.

Здравствуйте.
Будет ли обновляться коллекция запросов?
В данный момент коллекция актуальна для версии **2.5** но для **2.9** она не подходит, часть запросов отсутствует.

**Comment by ryanquinlan** [comment]
Admittedly this repo has been neglected 🙁

CMS 2.9 introduced a new API explorer feature that decreases the need to maintain this collection. Would be good to know, even with API explorer, is having a Postman collection still relevant for people?

**Comment by Izya12** [comment]
Relevant.
It is often much more convenient to use collection.

Актуальна.
Часто на много удобнее пользоваться collection.

**Comment by Izya12** [comment]
Will there be an update? already have 3.0
Будет ли обновление? уже есть 3.0

**Comment by ryanquinlan** [comment]
@Izya12 We just updated the repo to support CMS 3.0. Enjoy!
