### ISSUE TITLE
https://{{mmpHost}}/api/v1/coSpaces

### ISSUE THREAD

**Issue by ssv1907** [ciscocms/cms-postman-collection#5]
When I run this query I only get the first 20 coSpaces, not all! How to fix it?

**Comment by ryanquinlan** [comment]
Have a look at section 4.2.2 in the API [docs](https://www.cisco.com/c/dam/en/us/td/docs/conferencing/ciscoMeetingServer/Reference_Guides/Version-3-7/Cisco-Meeting-Server-API-Reference-Guide-3-7.pdf)

Most endpoints only return the first 10 or 20 elements. You need to use the offset query parameter to shift through the full list of elements.

As you'll see in the docs, the list can mutate while you are paging though it, so you may want to consider a different approach to the problem you're trying to solve for. Especially if you find yourself needing to enumerate large lists often.
